In [3]:
import numpy as np
Random=np.random.random((5,3))
print(Random)

[[0.02314824 0.46317132 0.50240798]
 [0.91653805 0.46905903 0.68499066]
 [0.39938607 0.23277154 0.48504437]
 [0.43716956 0.4192904  0.86318649]
 [0.89266583 0.58130999 0.55583461]]


In [4]:
zeros=np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
range=np.arange(5,31,2)
print(range)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)
print("\nDimension of this array : ",arr.ndim)
print("\nDatatype of this array : ",arr.dtype)
print("\nShape of this array : ",arr.shape)
print("\nFlatten array : ",arr.flatten())

[[1 2 3]
 [2 3 4]
 [3 4 5]]

Dimension of this array :  2

Datatype of this array :  int64

Shape of this array :  (3, 3)

Flatten array :  [1 2 3 2 3 4 3 4 5]
